spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/segelyhivo_simulator
spring.datasource.username=segelyhivo_app
spring.datasource.password=csatlosEQ9466
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=never

app.jwt.secret=EzEgyNagyonHosszuTitkosKulcsAJwtTokenekhezMinimum256BitHosszal123456789
app.jwt.expiration-ms=86400000